### ISSUE TITLE
Add fully asynchronous backend support.

### ISSUE THREAD

**Issue by Pilipets** [Smertig/banana#2]
How about adding fully asynchronous requests?
This is something that lacks in https://github.com/reo7sp/tgbot-cpp and https://github.com/slowriot/libtelegram.

Problem:
1. CPR allows calling synchronous libcurl from std::async, which isn't fully asynchronous.
2. boost::beast allows async requests, however coroutines may not be needed.

Solution:
1. Asynchronous libcurl looks like a good addition to the backend bundles - https://curl.se/libcurl/c/libcurl-multi.html;
2. Also boost beast without coroutines can be adopted here - https://www.boost.org/doc/libs/1_76_0/libs/beast/example/http/client/async/http_client_async.cpp

**Comment by Pilipets** [comment]
One more important thing to keep in mind is the message limit rate - https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this, which might be the reason the proposed functionality is not needed.

**Comment by Smertig** [comment]
> `boost::beast` allows async requests, however coroutines may not be needed.

Good catch! Callback-based or future-based async requests are probably the most popular options and should be definitely supported by `banana`. 

I've added experimental support for async requests in e299019e3832758e13ab213e0d810612dbcda779 (not yet documented). Two new connectors are available with `banana-beast` target:
 - `banana::connector::beast_future` - returns `std::future<T>` from API requests
 - `banana::connector::beast_future_monadic` - returns `std::future<banana::expected<T>>` from API requests

Its usage is quite simple:
```cpp
banana::connector::beast_future connector{ ... };

std::future<banana::message_t> result = banana::api::send_message(connector, { /* .chat_id = */ "@smertig", /* .text = */ "Hello, world!" });
// [Optionally] Block on std::future until the result is available
banana::message_t msg = result.get(); 
```

> One more important thing to keep in mind is the message limit rate - https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this, which might be the reason the proposed functionality is not needed.

I don't think this should be handled by `banana` itself.

There are too many limitations in telegram bot API anyway (i.e. message text should be 1-4096 characters _after parsing entities_). That should be checked by the developer, since `banana` is only a wrapper over API.

**Comment by Pilipets** [comment]
`I don't think this should be handled by banana itself.`
I agree, I added it in case you are not familiar with that limit.

Let me check the e299019.

Edited: `beast_future`, `beast_future_monadic` were the things I was referring to - nice.

**Comment by Pilipets** [comment]
Yes, that is just the thing I was refering to - nice.

**Comment by Smertig** [comment]
Updated docs: https://smertig.github.io/banana/master/api/banana/connectors/beast.html
